### ISSUE TITLE
Non-ascii chars cause Mash to crash

### ISSUE THREAD

**Issue by RMWChaos-duplicate** [Yacoby/Wrye-Mash#10]
WMSA85 will crash at open to Mods Tab with mod in \Data Files dir that have non-ascii characters in the name.

Repro:
1. With WMSA85 closed
2. Rename a plugin in \Data Files to this (cut/paste): òñë.esp
3. Open WMSA85

Result:
WMSA85 will briefly open a traceout window, but will close it before you can read it. Nothing captured in \Mopy\WryeMash.log; so I have no trace for you, sorry.

Workaround:
Removing the mod from \Data Files dir will allow WMSA85 to open normally.
Renaming the mod without non-ascii characters will allow WMSA85 to open normally.

Notes:
While it's very uncommon for mods to use non-ascii characters, there are a few that do. Tejòn's mods are a good example. His mods were the reason I was getting crashes with WMSA85 in the Installers Tab previously.

**Comment by Yacoby** [comment]
Converting a program to use Unicode is always going to be a bastard. I have fixed this issue by ensuring that all file names are Unicode objects. This may lead to other issues down the line though.

**Comment by Yacoby** [comment]
I have had to guess that Morrowind.ini is written to as latin-1. It seems (on my English game version) that it is but I am not 100% sure.
