### ISSUE TITLE
Error Enabling Installer Tab

### ISSUE THREAD

**Issue by ghost** [Yacoby/Wrye-Mash#20]
I get the following error when trying to enable the Installer tab:

```
Traceback (most recent call last):
  File "D:\games\Morrowind\Mopy\mash\masher.py", line 2326, in OnShowPage
    self.GetPage(event.GetSelection()).OnShow()
  File "D:\games\Morrowind\Mopy\mash\masher.py", line 1951, in OnShow
    modified = data.refresh(progress,what,self.fullRefresh)
  File "D:\games\Morrowind\Mopy\mash\mosh.py", line 4227, in refresh
    self.dictFile.load()
  File "D:\games\Morrowind\Mopy\mash\mosh.py", line 452, in load
    result = bolt.PickleDict.load(self)
  File "D:\games\Morrowind\Mopy\mash\bolt.py", line 750, in load
    self.data.update(cPickle.load(ins))
ImportError: No module named bolt
```

This seems to only happen when there's a bash directory with an Installers.dat file in the Installers directory when trying to enable the Installers tab for the first time.

I had Wrye Mash 84 installed previously, so the Installers.dat file was from that version, if that makes a difference.

Windows Version: 7 SP1 x64
Python Version: 2.7.2 x86
wxPython Version: 2.8.12.1 ANSI x86
comtypes Version: 0.6.2
Wrye Mash Version: 85-dev-56a4c37e33

**Comment by Yacoby** [comment]
I would assume this is because I have moved some of the classes around to
facilitate a better design of new code which breaks the old settings files.

I will try to add in code to support the older settings files

**Comment by ghost** [comment]
When I updated to the newer version of Mash, I deleted all of the old files in the "Data Files" and "Mopy" directories. So, this error must have something to do with the "Installers.dat" file that Mash-84 produces and Mash-85 trying to use/update it.
