### ISSUE TITLE
Mod Sorting: ESMs After ESPs

### ISSUE THREAD

**Issue by ghost** [Yacoby/Wrye-Mash#31]
When I try to reorder my mods, I can't get ESMs to load after ESPs, even if Sort by Type is disabled. Is there a reason for not allowing this?

I'm trying to get the TR ESMs to load after the official mods/plugins (which are ESPs). It's very likely that I just don't understand how MW handles mods/plugins, and that ESMs are loaded first followed by ESPs.

**Comment by Yacoby** [comment]
As far as I know (and I may be wrong) esms are always loaded first so you cannot get a esm to load after an esp.

**Comment by ghost** [comment]
I just reinstalled MW+EPs, so I'll play around with it and let you know what my findings are.

**Comment by ghost** [comment]
ESMs are always loaded first, even if an ESPs mod-date puts it before an ESM in Mash's mod list.

### Screens:

[![Modified-sorted mods in Wrye Mash 86.](http://img252.imageshack.us/img252/615/wryemash86modssort.th.png)](http://imageshack.us/photo/my-images/252/wryemash86modssort.png/)
[![The Elder Scrolls 3 Data Files dialog.](http://img33.imageshack.us/img33/8025/tes3datafilesdialogmods.th.png)](http://imageshack.us/photo/my-images/33/tes3datafilesdialogmods.png/)

**Comment by Yacoby** [comment]
Cheers for checking this
